services: #Container
  db:
    image: mysql
    container_name: mysql1
    networks:
      - beispiel-netzwerk
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=testdb
    volumes:
      - db_mysql_save:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 5s
      retries: 5

  backend:
    build: ./
    container_name: mein-backend
    volumes:
    
      - ./:/app
      - /app/node_modules
    networks:
      - beispiel-netzwerk
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy
        

volumes:
  db_mysql_save:
    
networks:
  beispiel-netzwerk:
    

